### ISSUE TITLE
sync to bundle not compatible with contentful-persistence

### ISSUE THREAD

**Issue by SDC-KurtTreangen** [contentful/contentful-utilities.swift#16]
contentful-utilities: 868db4e
contentful-persistence: 0.15.3

I am attempting to leverage the [seed db](https://github.com/contentful/contentful-persistence.swift/blob/8f799904585096ab2cda277a195fe0204b99a698/Sources/ContentfulPersistence/SynchronizationManager%2BSeedDB.swift#L24) functionality within contentful-persistence and am running into issues with the json files that are built using the `sync-to-bundle` command. 

contentful-persistence expects the entries to be in index named (1.json, etc) files and `sync-to-bundle` is only building a `entries.json` file. Furthermore, the entires in `entries.json` appear to only be partially built.

Is the [README](https://github.com/contentful/contentful-utilities.swift#next-steps) outdated as far as this is concerned? 

Please let me know if you need any more details.

**Comment by tomkowz** [comment]
Did you get a success message from the command-line? Should be something like this:
> Successfully stored JSON files for sync operation in directory 9udmtmq3klnj

In my case, it works fine and I am able to fetch all the date and all the related assets when `--download-asset-data` flag is specified.

Edit:
Indeed at some point this year, the contentful-utilities have been updated to produce `entries.json` instead of `0.json, 1.json` and so on. Also, there is a big mismatch of fetched data format and data format expected by the contentful-persistence.

I'll try to create PR to make Contentful Persistence to handle that file correctly.

How many entries there should be for you in the entries.json and how many there is?

**Comment by SDC-KurtTreangen** [comment]
Hello @tomkowz thanks for the response.

Yes, I do get the successful response.

I was not using the `--download-asset-data` flag but i just tried and that appears to have worked as it pulled down a lot of assets.

I have attached the two json files that I get from running the `sync-to-bundle` command. In `entries.json` I see entries for things but not their actual content / details.

[sync-to-bundle.zip](https://github.com/contentful/contentful-utilities.swift/files/5374049/sync-to-bundle.zip)

Edit: I rolled back to a previous version of contentful-utilities and was getting the entry details I would expect (`0.json`, `1.json`) but this was capped at just those two files. I assume this is related to this [issue](https://github.com/contentful/contentful-utilities.swift/issues/13).

**Comment by tomkowz** [comment]
Thanks! I see what's going on. Will work on the fix.

**Comment by tomkowz** [comment]
@SDC-KurtTreangen  I've created PR. I think you can access it and while waiting for a merge you could try to run it on your side and check whether that works for you.

**Comment by SDC-KurtTreangen** [comment]
@tomkowz I just tried it and received what looks like all of the entries in our Contentful space (7 json files). Will test more today but this appears to be fixed. Thank you!

**Comment by tomkowz** [comment]
We should be good then, no problem!
