### ISSUE TITLE
contentful-utilities & ContentfulPersistance

### ISSUE THREAD

**Issue by marcin-bo** [contentful/contentful-utilities.swift#4]
Hello,

I think that after latest updates seeding with `ContentfulPersistance` does not work. ContentfulPersistance looks for `space.json` and `contentful-utilities` output is `locales.json`.

**Comment by loudmouth** [comment]
Hi @marcin-bo 

Can you confirm that you're now using [`Contentful Persistence 0.11.0`](https://github.com/contentful/contentful-persistence.swift/releases/tag/0.11.0)? This new version consumes `locales.json` instead of `space.json` as there is now a locales endpoint on the Content Delivery API.

The only migration needs from 0.10.x to 0.11.0 are reinstalling contentful-utilities.swift, rerunning the command (see new instructions in readme as the command syntax has shifted slighlty) and using version 0.11.0 of the persistence lib.

**Comment by marcin-bo** [comment]
Hi, 

I was probably using Contentful Persistance 0.9.1 and that was the reason of the issue. I think we can close it.

Cheers!
